### PR TITLE
Activity_Login Updated 

### PR DESCRIPTION
**Pull request by joeyschen**
Changed the UI to make it look better.

### CODE REVIEW

**Comment by Dhsieh** [comment]
Why createLoginActivity3? why not use the original one?

**Comment by Dhsieh** [comment]
Can you put some pictures of the changes to the UI? Hard to see by looking at the code.

**Comment by joeyschen** [comment]
image

Ah sorry you don't need Login Activity 3... I forgot to delete it it was a test case.

**Comment by Dhsieh** [comment]
Okay cool, delete the test cases and i'll merge it

**Comment by joeyschen** [comment]
Updated with newest commit.

**Comment by Dhsieh** [comment]
Looks good

**Pull request merged**
